version: '3.9'

services:
  app:
    image: backend-engineering-case-study:1.0
    container_name: backend-engineering-case-study
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - 'local-network'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.35-oracle
    container_name: case-mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - 'local-network'
    ports:
      - '3308:3306'
    volumes:
      - case-mysql-data:/var/lib/mysql
      - ./mysql-db-dump.sql:/docker-entrypoint-initdb.d/mysql-db-dump.sql:ro

volumes:
  case-mysql-data:

networks:
  local-network:
    driver: bridge